import { Plan } from "./types/Plan";

export const data: Plan[] = [
	{
		duration: 4,
		locations: [
			{
				isBusiness: true,
				latitude: 0,
				longitude: 0,
				city: "Lauterbrunnen",
				country: "Switzerland",
				name: "Lauterbrunnen Valley Waterfalls",
				image:
					"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/1b/70/d9/das-lauterbrunnental.jpg?w=1200&h=-1&s=1",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				city: "Zürich",
				country: "Switzerland",
				name: "Zürich Lake",
				image: "https://www.newlyswissed.com/wp-content/uploads/2016/06/Strandbad-Mythenquai-01.jpg",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				city: "Grindelwald",
				country: "Switzerland",
				name: "First Cliff Walk by Tissot",
				image:
					"https://fullsuitcase.com/wp-content/uploads/2020/05/Best-things-to-do-in-Grindelwald-First-First-Cliff-Walk.jpg.webp",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				city: "Gridelwald",
				country: "Switzerland",
				name: "Bachalpsee Lake",
				image: "https://swissfamilyfun.com/wp-content/uploads/2021/09/bachalpse-lake-mountain-view.jpg",
			},
		],
		payed_services: [],
		people_number_recommendation: 1,
	},
	{
		duration: 3,
		locations: [
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Lisboa",
				country: "Portugal",
				name: "Miradores",
				image: "https://viajes.nationalgeographic.com.es/medio/2014/10/17/awl_por6668_1333x2000.jpg",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Lisboa",
				country: "Portugal",
				name: "Fabrica LX",
				image: "https://viajes.nationalgeographic.com.es/medio/2018/05/07/lxfactory_7a678137.jpg",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Lisboa",
				country: "Portugal",
				name: "Castelo de Sao Jorge",
				image: "https://cms.infoportugal.info/media/pois/final/129/JRN.EC.24917-129188.jpg",
			},
		],
		payed_services: [
			{
				nights: 4,
				night_price: 40,
				city: "Lisboa",
				country: "Portugal",
				date: new Date(),
				duration: 1,
				flight_code: "",
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				time: new Date(),
				total_price: 300,
			},
		],
		people_number_recommendation: 5,
	},
	{
		duration: 6,
		people_number_recommendation: 4,
		locations: [
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Sevilla",
				country: "Spain",
				name: "Giralda",
				image: "https://www.mercerhoteles.com/photo/blog/45/1/sevilla-a-los-pies-de-la-giralda.jpg?w=1440",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Sevilla",
				country: "Spain",
				name: "Catedral de sevilla",
				image:
					"https://www.turismosevilla.org/sites/default/files/styles/grande_800x600_/public/2022-01/617-%286%29-SEVILLA-Catedral.JPG?h=895baa79&itok=LpK7HS_V",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Marruecos",
				country: "Spain",
				name: "Rabat",
				image: "https://www.frs.es/fileadmin/_processed_/3/7/csm_csm-frs-iberia-destinos-rabat_06cdf5682b.jpg",
			},
			{
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				street: "Calle Sésamo",
				street_number: 8,
				city: "Marruecos",
				country: "Spain",
				name: "Marruecos",
				image: "https://media.iatiseguros.com/wp-content/uploads/2018/12/04010253/que-hacer-en-marruecos-8.jpg",
			},
		],
		payed_services: [
			{
				nights: 4,
				night_price: 40,
				city: "Sevilla",
				country: "Spain",
				date: new Date(),
				duration: 1,
				flight_code: "",
				isBusiness: false,
				latitude: 0,
				longitude: 0,
				time: new Date(),
				total_price: 159,
			},
		],
	},
];
