import Head from 'next/head'
import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Header from '../components/Header/Header'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div style={{
		margin: 'auto',
		alignItems: 'center',
		maxWidth: '120rem',
		width: '90%'
	}}>
			<Head>
				<title>Astask</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
      <Component {...pageProps} />
    </div>
  )
}
