import Head from "next/head";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Astask</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Header />
			<Main />
		</div>
	);
}
